### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by Ipuch** [DeepGenX/CodeGenX-Pycharm#3]
Hi,

Thank you for this amazing feature, I've just installed it and I'm wondering if there is a way to set a shortcut in Pycharm to ask CodeGenX like for the Visual Studio version?

Also in the visual studio version we have to ask the codegenX in the code, so it reads everything before.
Do we have to copy the whole code written before to generate code ?

**Comment by jtydhr88** [comment]
hi, i already create the #2 here about shortcut. Since I am a bit busy recently I will work on this feature maybe this week.

**Comment by jtydhr88** [comment]
Oh, also see #1 about similar behavior as VS Code, this may need to more tricky and research, I will do it later.
